"""update to Post table

Revision ID: 156417ef8010
Revises: dc06f58c4d8f
Create Date: 2020-01-08 11:07:03.617718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156417ef8010'
down_revision = 'dc06f58c4d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
